### ISSUE TITLE
我不知道为什么tumblr，更新不了主题了。non-https 

### ISSUE THREAD

**Issue by xfmniao** [xfmniao/tumblr#1]
tumblr为什么喜欢这个？
https://img.pawoo.net/media_attachments/files/011/139/452/original/ae0c0cb915b35cb3.jpeg

**Comment by be-low** [comment]
你现在解决了吗，ta 这意思就是你的主题引用了一个非 HTTPS (大概就是 HTTP) 协议的资源。
你把 http:// 替换成 https:// 应该就可以解决了。

**Comment by xfmniao** [comment]
> 你现在解决了吗，ta 这意思就是你的主题引用了一个非 HTTPS (大概就是 HTTP) 协议的资源。
> 你把 http:// 替换成 https:// 应该就可以解决了。
11月之前可以任意保存。网络发什么了什么，未知问题
![0224185449](https://user-images.githubusercontent.com/32816874/53298232-d3562000-3865-11e9-8812-4a238c712d3a.png)

**Comment by xfmniao** [comment]
发现更新代码后首页信息流刷不出来
我自己又改了回去
我都没有随便改
 那是 #TumblrAPI
